### ISSUE TITLE
Dot is one box ahead for [0,440][i%2]

### ISSUE THREAD

**Issue by nmorse** [francisrstokes/bito#12]
Running `[0,440][i%2]` gives a tone when the dot is in first (GUI) box and then no tone for the second box.
This seems backwards if `i` is a base zero index.

Bug may be in canvas painting of the dot in box one step ahead of the audio?

**Comment by francisrstokes** [comment]
Hey @nmorse, thanks for opening the issue. Yeah I think you're right about it being off by one. Should be a simple fix 😄
